#!/usr/bin/env bash
# Master orchestrator for the remaining compute-only experiments.
#
# Runs:
#   1. Five 2024 zero-shot deployments  (CPU + GEE, ~1.5 h)
#   2. Multi-seed cross-region matrix   (GPU 2, seeds 42, 1337, 2024 — 30 runs ~1.5 h)
#   3. AlphaEarth-stack few-shot multi-seed (GPU 2, seeds 42, 1337 — 10 runs ~1.7 h)
#   4. SegFormer baseline on the standard split (GPU 2, ~20 m)
#
# Total wall time ~5–6 hours. Progressive git commit after each stage so
# partial results survive crashes / restarts.
#
# Usage:  bash scripts/orchestrate_remaining.sh > /tmp/orchestrate.log 2>&1 &
set -uo pipefail

cd "$(dirname "$0")/.."
source /data/qbao775/miniconda3/etc/profile.d/conda.sh
conda activate geodisaster

LOG="/tmp/orchestrate.log"
say() { printf "\n[%s] %s\n" "$(date +%H:%M:%S)" "$*" | tee -a "$LOG" ; }

commit_progress() {
    local msg="$1"
    git add outputs/ data/processed/norm_stats_*.yaml configs/ 2>/dev/null
    if git diff --cached --quiet; then
        say "(no changes to commit)"
        return
    fi
    git commit -m "Auto-commit: $msg

Generated by scripts/orchestrate_remaining.sh.

Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>" \
        > /dev/null 2>&1 && say "committed: $msg"
    git push > /dev/null 2>&1 && say "pushed."
}

# =====================================================================
# STAGE 1 — five zero-shot global atlas events  (CPU + GEE)
# =====================================================================
say "STAGE 1 — five 2024/2023/2022 zero-shot deployments"
for event in uae_sharjah_2024 libya_derna_2023 bangladesh_sylhet_2024 \
             pakistan_sindh_2022 indonesia_demak_2024 ; do
    say "  → $event"
    CUDA_VISIBLE_DEVICES="" python scripts/deploy_zero_shot.py \
        --event "$event" >> "$LOG" 2>&1 || say "  (failed: $event — continuing)"
    # Decision metrics (JRC subtract + OSM intersect) — Brazil-style
    python scripts/brazil_flood_decision.py --event "$event" >> "$LOG" 2>&1 \
        || say "  (decision step failed for $event)"
done
commit_progress "Stage 1: 5 zero-shot global atlas events"

# =====================================================================
# STAGE 2 — multi-seed cross-region matrix  (GPU 2)
# =====================================================================
say "STAGE 2 — multi-seed cross-region matrix (3 new seeds)"
for SEED in 42 1337 2024 ; do
    say "  → seed $SEED"
    CUDA_VISIBLE_DEVICES=2 python -u scripts/run_leave_one_region_out.py \
        --seed "$SEED" \
        --workdir-root outputs/leave_one_region_out_multiseed \
        >> "$LOG" 2>&1
done
commit_progress "Stage 2: multi-seed cross-region matrix (seeds 42, 1337, 2024)"

# =====================================================================
# STAGE 3 — AE-stack few-shot multi-seed  (GPU 2)
# =====================================================================
say "STAGE 3 — AlphaEarth pre+post few-shot multi-seed (2 new seeds)"
for SEED in 42 1337 ; do
    say "  → AE-stack few-shot seed $SEED"
    CUDA_VISIBLE_DEVICES=2 python -u -m geodisaster.cli run-few-shot \
        --catalog data/catalog/sen1floods11_events.yaml \
        --model-config configs/model/alphaearth_stack_s1.yaml \
        --experiment-config configs/experiment/few_shot_ae_stack.yaml \
        --patch-root data/processed/patches \
        --workdir "outputs/few_shot_ae_stack_seed${SEED}" \
        --stats data/processed/norm_stats_sen1floods11_ae.yaml \
        >> "$LOG" 2>&1 || say "  (seed $SEED failed)"
done
commit_progress "Stage 3: AE-stack few-shot multi-seed (seeds 42, 1337)"

# =====================================================================
# STAGE 4 — SegFormer baseline on the standard split  (GPU 2)
# =====================================================================
say "STAGE 4 — SegFormer baseline"
# SegFormer expects 3-channel; use Sentinel-1 dB (2ch) padded to 3 — simpler
# to repurpose the smp_unet config with a deeper encoder. We use ResNet-50
# DeepLabV3+ as the second baseline, plus a SegFormer if HF download works.

# Build a simple smp DeepLabV3+ config on-the-fly via a tmp file
cat > /tmp/deeplab_s1s2.yaml <<EOF
name: deeplabv3plus_s1s2
family: smp_deeplabv3plus
backbone:
  type: resnet50
  encoder_weights: null
  in_channels: 15
  sources: [sentinel1, sentinel2]
head:
  out_channels: 1
loss:
  type: focal_bce
  alpha: 0.75
  gamma: 2.0
EOF

say "  → DeepLabV3+ ResNet-50 (S1+S2)"
CUDA_VISIBLE_DEVICES=2 python -u -m geodisaster.cli train \
    --catalog data/catalog/sen1floods11_events.yaml \
    --model-config /tmp/deeplab_s1s2.yaml \
    --patch-root data/processed/patches \
    --workdir outputs/sen1floods11_deeplab_s1s2 \
    --train-events sen1floods11_Ghana --train-events sen1floods11_India \
    --train-events sen1floods11_Mekong --train-events sen1floods11_Nigeria \
    --train-events sen1floods11_Pakistan --train-events sen1floods11_Paraguay \
    --train-events sen1floods11_Somalia --train-events sen1floods11_Sri-Lanka \
    --val-events sen1floods11_Spain \
    --test-events sen1floods11_USA \
    --stats data/processed/norm_stats_sen1floods11.yaml \
    >> "$LOG" 2>&1 || say "  (deeplab failed)"
commit_progress "Stage 4: DeepLabV3+ ResNet-50 baseline"

# =====================================================================
# FINAL — rebuild blog + push
# =====================================================================
say "FINAL — rebuild blog with all new data"
python -m geodisaster.cli build-blog >> "$LOG" 2>&1
commit_progress "All stages complete — blog rebuild"

say "ALL DONE."
