#!/usr/bin/env bash
# Run active region adaptation across all 10 Sen1Floods11 regions, then
# aggregate into a smart-vs-random summary with confidence intervals.
#
# Each region uses its leave-one-out base model (trained WITHOUT that region)
# as the zero-shot starting point, then adapts with a small label budget.
#
# Usage: bash scripts/run_all_region_adapt.sh > /tmp/all_adapt.log 2>&1 &
set -uo pipefail
cd "$(dirname "$0")/.."
source /data/qbao775/miniconda3/etc/profile.d/conda.sh
conda activate geodisaster

GPU=6
LOG=/tmp/all_adapt.log
say() { printf "\n[%s] %s\n" "$(date +%H:%M:%S)" "$*" | tee -a "$LOG"; }

REGIONS=(Ghana India Mekong Nigeria Pakistan Paraguay Somalia Spain Sri-Lanka USA)

for r in "${REGIONS[@]}"; do
    if [ -f "outputs/active_adapt/adapt_${r}.json" ]; then
        say "SKIP $r (already done)"
        continue
    fi
    ck=$(ls -t "outputs/leave_one_region_out/test_${r}/checkpoints/"*.ckpt 2>/dev/null | head -1)
    if [ -z "$ck" ]; then
        say "SKIP $r (no base checkpoint)"
        continue
    fi
    say "ADAPT $r  (base=$(basename "$ck"))"
    CUDA_VISIBLE_DEVICES=$GPU python -u scripts/active_region_adapt.py \
        --region "$r" \
        --base-ckpt "$ck" \
        --budgets 1,4,8 \
        --random-seeds 0,1 \
        --epochs 20 >> "$LOG" 2>&1 || say "  (failed: $r)"
done

say "AGGREGATE + render summary figure"
python scripts/aggregate_region_adapt.py >> "$LOG" 2>&1

# commit + push small artefacts
git add outputs/active_adapt/*.json outputs/figures/fig11_region_adapt_summary.png \
        outputs/site/index.html outputs/site/dashboard.html 2>/dev/null
git commit -m "All-region active adaptation: smart-vs-random across 10 regions

Generated by scripts/run_all_region_adapt.sh.

Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>" > /dev/null 2>&1 && say "committed"
timeout 90 git push > /dev/null 2>&1 && say "pushed" || say "push skipped/failed"
say "ALL-REGION ADAPT DONE."
